//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FTC_Timer_Display.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class logging : global::System.Configuration.ApplicationSettingsBase {
        
        private static logging defaultInstance = ((logging)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new logging())));
        
        public static logging Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool logMatchDataChanges {
            get {
                return ((bool)(this["logMatchDataChanges"]));
            }
            set {
                this["logMatchDataChanges"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logInitialSetupSteps {
            get {
                return ((bool)(this["logInitialSetupSteps"]));
            }
            set {
                this["logInitialSetupSteps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool logSingleClientChanges {
            get {
                return ((bool)(this["logSingleClientChanges"]));
            }
            set {
                this["logSingleClientChanges"] = value;
            }
        }
    }
}
